name: yuvimage
description: Simple Dart library for manipulating yuv images from camera
version: 0.0.2
homepage: null
publish_to: null

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: